### ISSUE TITLE
新版本无法正确在一些游戏中加载

### ISSUE THREAD

**Issue by PiDanShouRouZhouXD** [fkiliver/SakuraTranslator#11]
![image](https://github.com/fkiliver/SakuraTranslator/assets/38401147/bf81ba5a-4c93-434b-bdb6-1523a06ef484)
推测原因是内置的Newtonsoft与插件的版本不兼容导致，我应该如何才能正常运行？
一些参考：
https://forum.unity.com/threads/newtonsoft-json-package.843220/

**Comment by fkiliver** [comment]
> ![image](https://private-user-images.githubusercontent.com/38401147/330940507-bf81ba5a-4c93-434b-bdb6-1523a06ef484.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5OTk2MjQsIm5iZiI6MTcxNTk5OTMyNCwicGF0aCI6Ii8zODQwMTE0Ny8zMzA5NDA1MDctYmY4MWJhNWEtNGM5My00MzRiLWJkYjYtMTUyM2EwNmVmNDg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDAyMjg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlMmEzYmI3NTUyNDA4MmM3NTA1YWQyNjZlYmY2ZDYzMGY3MjBmNmIxYWFiNWQ0M2NkMTBjNWMxMzRiZWZkYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8hUhfC5cUAVlz8Jsh0KYEaBC86xXjQDaTsSFOB8jW0k) 推测原因是内置的Newtonsoft与插件的版本不兼容导致，我应该如何才能正常运行？ 一些参考： https://forum.unity.com/threads/newtonsoft-json-package.843220/

什么游戏

**Comment by fkiliver** [comment]
0.3.6已解决
