### ISSUE TITLE
无法加载

### ISSUE THREAD

**Issue by HolyWarL** [fkiliver/SakuraTranslator#12]
![K7G$W4(6S1U_AAW6A6 2B$V](https://github.com/fkiliver/SakuraTranslator/assets/170143614/9a6efe10-dfa7-4ace-8a66-f30734e0da6a)
Bepinex版本5.23.1

**Comment by HolyWarL** [comment]
但是很神奇，v0.2.2就可以

**Comment by fkiliver** [comment]
> ![K7G$W4(6S1U_AAW6A6 2B$V](https://private-user-images.githubusercontent.com/170143614/331736374-9a6efe10-dfa7-4ace-8a66-f30734e0da6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5OTk1MjMsIm5iZiI6MTcxNTk5OTIyMywicGF0aCI6Ii8xNzAxNDM2MTQvMzMxNzM2Mzc0LTlhNmVmZTEwLWRmYTctNGFjZS04YTY2LWYzMDczNGUwZGE2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOFQwMjI3MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYjU4YWZlMDNmNWM1YTU2NjU5ZmZmMGE5MWUwOThlMGRlZGFlZWQwMTgyMWY1NGU4MGQ5Y2M5YmI2MWFjMTVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FIP81_2O4OlVXekvOuYHJIf5uULYafDxDdgxRICpK4o) Bepinex版本5.23.1

什么游戏

**Comment by HolyWarL** [comment]
Koikatsu（KK）不行，sunshine（kks）貌似可行

**Comment by BrokenMyth** [comment]
> 但是很神奇，v0.2.2就可以

我2.2也用不了

**Comment by fkiliver** [comment]
0.3.6已解决
