### ISSUE TITLE
有些游戏快捷键alt+0打不开开翻译面板，有没有替代方法

### ISSUE THREAD

**Issue by as176590811** [fkiliver/SakuraTranslator#3]
有些游戏快捷键alt+0打不开开翻译面板，有没有替代方法

**Comment by fkiliver** [comment]
不该打不开吧，是不是没生效，换个注入方式试试。看下目录下有没有生成配置文件，如果生成了可以直接在里面改翻译器

**Comment by as176590811** [comment]
> 不该打不开吧，是不是没生效，换个注入方式试试。看下目录下有没有生成配置文件，如果生成了可以直接在里面改翻译器

生效了，游戏能用谷歌翻译。但就是打不开面板。这也不是一次两次了，遇到过能打开的不能打开的也遇到

**Comment by fkiliver** [comment]
> > 不该打不开吧，是不是没生效，换个注入方式试试。看下目录下有没有生成配置文件，如果生成了可以直接在里面改翻译器
> 
> 生效了，游戏能用谷歌翻译。但就是打不开面板。这也不是一次两次了，遇到过能打开的不能打开的也遇到

那就直接改配置文件吧，第二行就是调用什么翻译器

**Comment by as176590811** [comment]
修改AutoTranslatorConfig.ini中
[Service]
Endpoint=SakuraTranslator
FallbackEndpoint=
解决问题
