### ISSUE TITLE
不支持kaggle网站的链接？

### ISSUE THREAD

**Issue by mhaas6** [fkiliver/SakuraTranslator#4]
利用kaggle搭建sakura-13b-lnovel-v0.9b-Q8_0模型，请求失败，kaggle未收到任何请求。没有报错信息不清楚哪里出了问题................

**Comment by fkiliver** [comment]
暂时没有写kaggle支持

**Comment by mhaas6** [comment]
> 检查autotranslator的配置文件 [Sakura] Endpoint=http://127.0.0.1:8080/completion ##这里修改为你的模型server监听的地址 ApiType=Qwen ##Qwen为Sakura 0.9模型，空置则为Sakura 0.8
> 
> 理论上endpoint改为你kaggle的Sakura API就可以了

我以确认我的设置没有问题，我尝试在本地搭建这个模型，调用正常。但当我把Endpoint改为kaggle提供的链接，翻译器无法工作。（链接是有效的已测试）

**Comment by fkiliver** [comment]
> > 检查autotranslator的配置文件 [Sakura] Endpoint=http://127.0.0.1:8080/completion ##这里修改为你的模型server监听的地址 ApiType=Qwen ##Qwen为Sakura 0.9模型，空置则为Sakura 0.8
> > 理论上endpoint改为你kaggle的Sakura API就可以了
> 
> 我以确认我的设置没有问题，我尝试在本地搭建这个模型，调用正常。但当我把Endpoint改为kaggle提供的链接，翻译器无法工作。（链接是有效的已测试）

好的，我去搞个kaggle测试一下

**Comment by fkiliver** [comment]
已增加对kaggle支持，请查看[[Releases](https://github.com/fkiliver/SakuraTranslator/releases)](https://github.com/fkiliver/SakuraTranslator/releases/tag/v0.2.2)
