### ISSUE TITLE
没理解具体怎么安装

### ISSUE THREAD

**Issue by ponkora** [fkiliver/SakuraTranslator#5]
希望大佬可以提供更详细的教程
Sakura模型已经完成部署了，现在卡在SakuraTranslator.dll具体是放在哪个文件夹内的问题

尝试过BepInEx、UnityInjector等版本的XUnity并放在其中的Translators
![{65EDF4A9-78E2-448d-BDF8-CF2B53E1B514}](https://github.com/fkiliver/SakuraTranslator/assets/93536394/2533083e-d752-4859-9702-0a17ace5d4ca)

然后启动游戏，在新生成的AutoTranslator中Config.ini无法找到Sakura相关设置
且再次启动游戏中的XUnity也无法找到Sakura翻译

**Comment by fkiliver** [comment]
是不是你游戏本体已经有ReiPatcher版本了，检查：游戏名_Data\Managed\Translators

**Comment by ponkora** [comment]
> 是不是你游戏本体已经有ReiPatcher版本了，检查：游戏名_Data\Managed\Translators

奥奥，确实是
