### ISSUE TITLE
Sakura v0.10字典注释

### ISSUE THREAD

**Issue by Tabing010102** [fkiliver/SakuraTranslator#7]
貌似发现v0.10字典的注释可能能纠正（指定）翻译的人物性别
但模型目前还不是稳定发布版，等模型稳定了可以考虑把注释的支持也加上

![image](https://github.com/fkiliver/SakuraTranslator/assets/21260494/f5608e9e-3e83-4514-9e12-677dd9b5734d)

**Comment by fkiliver** [comment]
整挺好，我现在也是在等0.10稳定版，然后把退化检测也加进去
